### ISSUE TITLE
Document clear definition of each of the config variables

### ISSUE THREAD

**Issue by andrewphilipsmith** [PandemiaProject/pandemia#11]
- [x] Minimum of *most* important variables to tweak / typical changes
- [x] Make clear which params are vital

**Comment by AoifeHughes** [comment]
Branch: https://github.com/PandemiaProject/pandemia/tree/documentation 

@James-Thompson-724 if you want to @ me once this is ready to be merged then I can review and handle!

**Comment by James-Thompson-724** [comment]
@AoifeHughes Hi Aoife, I'd like to merge the documentation branch into the develop branch now. Could you review and handle this, as you suggested? Thanks!
