### ISSUE TITLE
Automate end-to-end testing

### ISSUE THREAD

**Issue by andrewphilipsmith** [PandemiaProject/pandemia#12]
Use the existing scenarios to create automated test:

- [ ] Identify which _*minimum*_ combination of scenarios that exercises all of the functionality.
- [ ] If necessary, contrive additional scenarios to test any remaining functionality
- [x] Create "gold standard" simulation outputs.
- [x] Create a programmatic way to compare the gold standard outputs with future runs (e.g. ignore timestamps, floating point rounding error etc as appropriate)
 - [x] Implement in GH Acitons or simular platform.
 - [x] Add any additional requirements for testing to `setup.py`
 - [x] Add instructions/info about end-to-end tests to relevant docs

**Comment by andrewphilipsmith** [comment]
@AoifeHughes Please could you run this scenario on Windows:

`Scenarios/Test/test_global_config.yaml`

Ant then share the output file with me (it should be written to `tests/e2e_outputs/strain_counts.csv`)

**Comment by AoifeHughes** [comment]
@andrewphilipsmith - [tests.zip](https://github.com/PandemiaProject/pandemia/files/10084073/tests.zip)

**Comment by AoifeHughes** [comment]
Did you expect all 0's?

**Comment by andrewphilipsmith** [comment]
THanks @AoifeHughes, just what I needed.
