### ISSUE TITLE
Restructure docs - potentially seperate User Docs and Contributors Docs

### ISSUE THREAD

**Issue by andrewphilipsmith** [PandemiaProject/pandemia#26]
**Suggested structure**

Readme
- Orientation
- Project overview / acknowledgements
- Pointers to other docs

User Guide:
- Quick start / Install
- Inputs and Outputs
- Detailed User Guide
- Scientific background

Contributors Docs:
- The general structure of the code
- Legacy of AMBLux model
- Testing (end-to-end and unit test)
- Comments on aspirations for future development as well as the legacy of previous code.

**Comment by James-Thompson-724** [comment]
The docs have now been restructured using reStructuredText and Sphinx. Contributor docs can be found in the Readme
