### ISSUE TITLE
Create headerless running config

### ISSUE THREAD

**Issue by AoifeHughes** [PandemiaProject/pandemia#36]
It might be worth investigating if the GUI can have a toggle - could be nice to convert pygame to an option dependency (this would make future proofing easier and one less "awkward" library to watch for. Also could make it easier to run on HPCs etc if this was something someone wanted to do a massive ammount of simulation work.

**Comment by AoifeHughes** [comment]
I'm thinking about this as a I debug the simulator package, so maybe will have a better idea soon as to if this is doable.

**Comment by AoifeHughes** [comment]
- TODO @AoifeHughes  check if this is documentated

**Comment by andrewphilipsmith** [comment]
The tests used with end-to-end tests are all headless at the moment. These can be used as examples.
