### ISSUE TITLE
Change agent status to a boolean array - could save a bunch of memory and faster at moving from python->C->python

### ISSUE THREAD

**Issue by AoifeHughes** [PandemiaProject/pandemia#37]

**Comment by AoifeHughes** [comment]
Needs properly thought about but could be a really easy refactoring change to shave off a lot of memory bandwidth (could also let some fancy numpy matrix fun happen)

**Comment by James-Thompson-724** [comment]
This won't save a huge amount of memory, since boolean variables are relevant for only a few 1-dimensional arrays (with a few million agents, the memory saved would be a few tens of megabytes, while the total memory usage is tens of gigabytes).
