### ISSUE TITLE
`InputModel` name is ambiguous

### ISSUE THREAD

**Issue by andrewphilipsmith** [PandemiaProject/pandemia#46]
The name `InputModel` is ambiguous.

This could be understood to mean the inputs (or initial state) of the model.

`PolicyInterventionModel` or something similar might be more descriptive.

**Comment by James-Thompson-724** [comment]
I'm going to change this to `PolicyMakerModel`, I think

**Comment by James-Thompson-724** [comment]
I'm going to change this to something like `PolicyMakerModel`

**Comment by James-Thompson-724** [comment]
Renamed `InputModel` to `PolicyMakerModel` etc: https://github.com/PandemiaProject/pandemia/commit/9440f91b5a07c6b36cb2ffe77312fdcd3012e5c7
