### ISSUE TITLE
ASCII Grid writer method produces incorrect header

### ISSUE THREAD

**Issue by andrewphilipsmith** [PandemiaProject/pandemia#47]
# How to reproduce

Use `./Scenarios/Global_Grid/data/country_data_population_distribution/extractor.py` to create ASCII grids.

Open an output file in a text editor and observe the header

# Actual header

```
ncols 26
nrows 15
xllcorner -63
yllcorner 18
square_width 0.041666666666667
NODATA_value -9999
```

# Expected header

```
ncols 26
nrows 15
xllcorner -63
yllcorner 18
cellsize 0.041666666666667
NODATA_value -9999
```

Note `cellsize` rather than `square_width`.

Fixing the header in the ascii grid allows the files to be opened in a third-party software such as QGIS.

**Comment by James-Thompson-724** [comment]
Renamed `square_width` to `cellsize`.
