### ISSUE TITLE
parameters not intialiatised in VoidHealthModel

### ISSUE THREAD

**Issue by andrewphilipsmith** [PandemiaProject/pandemia#49]
# Error

TBC

# Notes

In order to get the end-to-end tests working, is was necessary to move this code from `DefaultHeathModel.vectorize_component()`

```
# vector_region.current_disease = np.zeros((number_of_agents), dtype=float)
# vector_region.current_strain = np.full((number_of_agents), -1, dtype=int)
```

into `VectorRegion.__init__()`

```
self.current_disease = np.zeros((number_of_agents), dtype=float)
self.current_strain = np.full((number_of_agents), -1, dtype=int)
```

But, note this quote from the VectorRegion constructor:

>     """Contains vector representations of agents, locations and other objects. Additional
    attributes are initialized by the simulation components, for example the health model,
    inside their vectorize_component function."""

Is VectorRegion the right place for this, or should it be duplicated in `VoidHealthModel`?

**Comment by andrewphilipsmith** [comment]
Similar issues exist for other component/vectorregion attribute combinations.

```
FAILED tests/test_end_to_end_pandimia.py::test_e2e_hospitalization_and_death_model - AttributeError: 'VectorRegion' object has no attribute 'requesting_location_update'
FAILED tests/test_end_to_end_pandimia.py::test_e2e_testing_and_contact_tracing_model - AttributeError: 'VectorRegion' object has no attribute 'home_location'
```

**Comment by James-Thompson-724** [comment]
All components have now been updated to resolve this issue (see https://github.com/PandemiaProject/pandemia/commit/5f40c20aeb007d3ef21f3ffb813532e4b4503bdb). In particular, all necessary attributes are now initialized in the corresponding void models.
