### ISSUE TITLE
How should VectorRegions name, id and iso code attributes interact?

### ISSUE THREAD

**Issue by andrewphilipsmith** [PandemiaProject/pandemia#52]
Opinion:

To me, it seems that the meaning of the `.name` and `.id` attributes in VectorRegions is not clear. As far as I can tell:

These seem to be defined from the data read from the `regions_data_file`, `regions_shape_path` and `regions_shape_data_file` OR the `world_factory.region_names` parameter.

* If there is and csv file `regions_data_file` but no shapefile:
Then the `.name` and `.id` are set from the `regions_data_file` csv file. The column numbers are hardcoded.

* If there is a shapefile (`regions_shape_path` or `regions_shape_data_file`) specified AND the region exists in the shapefile:
  - `.name` is set to be the first column of the shapefile. The value assumed to be an ISO code is cleaned for certain hardcoded known ISO code ambiguities.

* If there is a shapefile (`regions_shape_path` or `regions_shape_data_file`) specified AND the region DOES NOT exist in the shapefile:
  - `.name` remains as set from the regions_data_file` csv file. 

* If none of regions_data_file`, `regions_shape_path` and `regions_shape_data_file` are specified:
   - Both the `.name` and `.id` attributes are set from the `world_factory.region_names` parameter.
   - In this case it is not possible to have independent values for `.name` and `.id`

Additionally:

* Region.id is an int
* VectorRegion.id is a str

The code explicitly refers to ISO values, though it is necessary that the region id is an ISO code. It is possible to define some data files (eg `seasonal_multiplier_by_region_by_month`) which have non-unique IDs which silently fail. It would be helpful to explicitly enforce that this id is unique in any input data.

For testing purposes with fictional territories, it would be helpful to be able to use the NATO extension to ISO2 standard that allows for fictional countries.

**Comment by andrewphilipsmith** [comment]
Using NATO country code (which are a defacto extension of the ISO country codes standard) allows for fictional countries https://en.wikipedia.org/wiki/List_of_NATO_country_codes

**Comment by James-Thompson-724** [comment]
regions_shape_path is now renamed regions_shape_data_file in the default_input_model branch

**Comment by James-Thompson-724** [comment]
The id column has now been removed from the seasonality data file: https://github.com/PandemiaProject/pandemia/commit/140839020011986519a8186a3552b9e2c0391c7d

**Comment by James-Thompson-724** [comment]
Additionally, VectorRegion.id is definitely now an int
