### ISSUE TITLE
Inconsistant parameter name `regions_shape_path` vs `regions_shape_data_file`

### ISSUE THREAD

**Issue by andrewphilipsmith** [PandemiaProject/pandemia#53]
`regions_shape_path` - used in 
DefaultWorldFactory
GlobalWorldFactory

`regions_shape_path` - used in 
GlobalGridWorldFactory

**Comment by James-Thompson-724** [comment]
regions_shape_path is now renamed regions_shape_data_file in the default_input_model branch
