### ISSUE TITLE
Optimise data type sizes

### ISSUE THREAD

**Issue by AoifeHughes** [PandemiaProject/pandemia#61]

**Comment by AoifeHughes** [comment]
A lot of the numpy arrays are 64 bit and could easily be made smaller e.g., 32bit ints, boolean arrays etc. This needs investigating!

**Comment by AoifeHughes** [comment]
with respect to https://github.com/orgs/PandemiaProject/projects/1/views/1?pane=item&itemId=14990004

**Comment by AoifeHughes** [comment]
Just on this, I think there could be another optimisation done by stopping as much casting going on - essentially every `.astype` command could be set when the variable is defined. Maybe...

**Comment by AoifeHughes** [comment]
![Image](https://user-images.githubusercontent.com/10923695/211273958-41b735b2-da5a-4efa-829a-29122d4e2041.svg)

**Comment by AoifeHughes** [comment]
Current profilling from running `pytest -x -m slow -k "test_end_to_end_global" --profile-svg` on https://github.com/PandemiaProject/pandemia/commit/11112a60560a585e0c7dcb293e70ea5e1bf796f9

**Comment by James-Thompson-724** [comment]
Wow that visualization is pretty cool

**Comment by AoifeHughes** [comment]
Yeah! I haven't had a chance to dig into this properly yet! But it's how I'll start working out where's best to focus and work outwards.

**Comment by James-Thompson-724** [comment]
See also my latest comment on this issue:
https://github.com/PandemiaProject/pandemia/issues/63

**Comment by James-Thompson-724** [comment]
Switching to boolean arrays won't make a huge different, however switching from 64 bit integers to 32 bit integers does, so the latter has been implemented. Floats are still double precision, to minimize errors.
