### ISSUE TITLE
Approximate matching for test outputs is too vauge

### ISSUE THREAD

**Issue by andrewphilipsmith** [PandemiaProject/pandemia#70]
Two tests use approximate matching to assert that the test output matches the gold standard output (`test_end_to_end_all_components` and `test_e2e_testing_and_contact_tracing_model`). These tests have been marked using the `@pytest.mark.approx_matching` decorator.

Currently, the acceptable margins are very large (either +/- 100 absolute values, or +/- 50% relative values). The are applied on a per-test basis using the decorator `@pytest.mark.parametrize("rel_tol, abs_tol", [(0.5, 100)])` on the relevant tests.

These margins were OK for the purpose of establishing the tests, but don't provide much meaningful insight into whether the model behaviour is acceptable or not.

These values should be revised, with modelling expertise into what is appropriate, acceptable model behaviour.

**Comment by James-Thompson-724** [comment]
The tests `test_end_to_end_all_components` and `test_e2e_testing_and_contact_tracing_model` now do not require approximate matching to pass, now that the underlying issue in the default contact tracing model has been fixed.
