### ISSUE TITLE
Remove the old documentation dir "docs-pdoc3"

### ISSUE THREAD

**Issue by andrewphilipsmith** [PandemiaProject/pandemia#78]
Whilst implementing the documentation workflow in sphinx, the old documentation was moved to "docs-pdoc3". Initially, this directory was left so that the transformation from LaTeX+markdown -> reStructuredText could be manually checked. 

Once this manual checking has been completed, the old "docs-pdoc3" should be removed.

**Comment by James-Thompson-724** [comment]
Done.
