### ISSUE TITLE
Pull in-progress branches into develop and into main

### ISSUE THREAD

**Issue by AoifeHughes** [PandemiaProject/pandemia#82]

**Comment by AoifeHughes** [comment]
- [ ] https://github.com/PandemiaProject/pandemia/tree/warnings/compile
- [ ] https://github.com/PandemiaProject/pandemia/tree/docs/docstrings
- [ ] https://github.com/PandemiaProject/pandemia/tree/fix/update-flake-test-name
- [ ] https://github.com/PandemiaProject/pandemia/tree/test/sample-unittests

**Comment by AoifeHughes** [comment]
- [ ] Update workflow in .github

**Comment by James-Thompson-724** [comment]
Done.
